package presentacion;

import logica.Jugador;
import logica.Fichero;
import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;



public class Registro extends javax.swing.JFrame {
    /** Atributo que permite leer y guardar los datos del jugador */
    private Fichero lecEscr ;
    /** Atributo que relaciona ciertos componentes del inicio con la interfaz */
    private MenuInicio inicio;
    
    
    /** Constructor de Registro
     * @param inicio pantalla de inicio
     * @throws java.io.FileNotFoundException señala que un intento de abrir el archivo
        * indicado por un nombre de ruta especificado ha fallado
     * @throws java.lang.ClassNotFoundException se lanza cuando una aplicación intenta cargar en una clase a través de su 
         * nombre de cadena usando ciertos métodos de los cuales no se puede encontrar una para la clase con el nombre especificado.
     */
    public Registro(MenuInicio inicio) throws IOException, FileNotFoundException, ClassNotFoundException {
        this.inicio = inicio;
        lecEscr = new Fichero();
        
        initComponents();
        botonesTransparentes();
        
        this.setLocationRelativeTo(this.inicio);
        this.setVisible(true);
        this.setIconImage(new ImageIcon("src/images/icono.png").getImage());
        lecEscr.leerDatos();
        jDialog1.setIconImage(new ImageIcon("src/images/icono.png").getImage());
        
        ImageIcon dSure = new ImageIcon("src/images/fondo.jpg");
        ImageIcon sure = new ImageIcon(dSure.getImage().getScaledInstance(dialogo.getWidth(), dialogo.getHeight(),Image.SCALE_DEFAULT));
        dialogo.setIcon(sure);
        
        ImageIcon reg = new ImageIcon("src/images/fondo.jpg");
        ImageIcon Reg = new ImageIcon(reg.getImage().getScaledInstance(regi.getWidth(), regi.getHeight(),Image.SCALE_DEFAULT));
        regi.setIcon(Reg);
    }
    
    /** Método que permitirá poner los botones de la interfaz transparentes
     */
    public void botonesTransparentes(){
        jButton2.setOpaque(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setBorderPainted(false);
        
        jButton3.setOpaque(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setBorderPainted(false);
        
        aceptar.setOpaque(false);
        aceptar.setContentAreaFilled(false);
        aceptar.setBorderPainted(false);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jDialog1 = new javax.swing.JDialog();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        dialogo = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        aceptar = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        regi = new javax.swing.JLabel();

        jLabel3.setFont(new java.awt.Font("DejaVu Sans Mono", 0, 24)); // NOI18N
        jLabel3.setText("NOMBRE");

        jDialog1.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jDialog1.setMinimumSize(new java.awt.Dimension(490, 193));
        jDialog1.setResizable(false);
        jDialog1.getContentPane().setLayout(null);
        jDialog1.getContentPane().add(jLabel6);
        jLabel6.setBounds(60, 20, 400, 37);

       
        jDialog1.getContentPane().add(jLabel7);
        jDialog1.getContentPane().add(jLabel2);
        jLabel2.setBounds(130, 50, 220, 30);

       
        jDialog1.getContentPane().add(aceptar);
        jButton2.setBounds(80, 120, 68, 32);

    
        jDialog1.getContentPane().add(jButton3);
        jButton3.setBounds(330, 120, 73, 32);

        dialogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/dialogo2.jpg"))); // NOI18N
        dialogo.setMaximumSize(new java.awt.Dimension(500, 200));
        jDialog1.getContentPane().add(dialogo);
        dialogo.setBounds(0, 0, 500, 220);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(246, 249, 251));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(678, 427));
        getContentPane().setLayout(null);

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3);
        jTextField3.setBounds(270, 240, 300, 40);

        aceptar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        aceptar.setText("Registrar");
        aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarActionPerformed(evt);
            }
        });
        getContentPane().add(aceptar);
        aceptar.setBounds(210, 310, 240, 70);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(270, 170, 300, 40);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Indique su DNI:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(110, 250, 160, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Indique su nombre de Usuario:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 180, 250, 30);

        regi.setMaximumSize(new java.awt.Dimension(678, 427));
        regi.setMinimumSize(new java.awt.Dimension(678, 427));
        getContentPane().add(regi);
        regi.setBounds(0, 0, 678, 427);

        pack();
    }// </editor-fold>

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }
    /** Método que, al pulsar el botón aceptar, nos mostrará un cuadro de diálogo con los datos
     * recién introducidos para confirmar el registro
     */
    private void aceptarActionPerformed(java.awt.event.ActionEvent evt) {
        String dni = jTextField3.getText().toUpperCase();
        String nombre = jTextField4.getText().toUpperCase();
        
        lecEscr.añadirJugador(new Jugador(nombre,dni));
        Jugador j = lecEscr.buscarJugador(dni);
        try {
            lecEscr.guardarDatos();
        } catch (IOException ex) {
            Logger.getLogger(Registro.class.getName()).log(Level.SEVERE, null, ex);
        }
              
        this.dispose();
        jDialog1.dispose();

          int YesOrNo = JOptionPane.showConfirmDialog(null,"¿Quieres registrarte con este usuario y DNI?", " ",JOptionPane.YES_NO_OPTION);
         this.setIconImage(new ImageIcon("src/images/icono.png").getImage());
          if(YesOrNo == 0)
        {  MenuJuego mj = new MenuJuego(j);
            inicio.dispose();
            }else{
         dispose(); 
         
        
    }
    
    }
    
    
    
    
    private javax.swing.JButton aceptar;
    private javax.swing.JLabel dialogo;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JLabel regi;

}
